#!/usr/bin/env bash

set -e # exit on first error

CONFIG="install.yaml"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_BIN="${HERE}/dotbot/bin/dotbot"

function submodule_update {
  cd "${HERE}"
  git submodule sync --recursive
  git submodule update --init --recursive
}

function install {
  "${DOTBOT_BIN}" -d "${HERE}" -c "${CONFIG}" "${@}"
}

# Update submodules
submodule_update
# Install dotfiles
install